import React, { useState } from 'react';

const EmailTemplate = () => {
  const [selectedTemplate, setSelectedTemplate] = useState('forgotpassword');

  const handleTemplateChange = (e) => {
    setSelectedTemplate(e.target.value);
  };

  // Sample values for variables to avoid the "undefined" error
  const templateVariables = {
    user: '{user}',
    email: '{email}',
    password: '{password}',
    username: '{username}',
    customername: '{customername}',
    ordernumber: '{ordernumber}',
    orderdate: '{orderdate}',
    grandtotal: '{grandtotal}',
    track_order_url: '{track_order_url}',
    adminname: '{adminname}',
  };

  const getTemplateContent = () => {
    if (selectedTemplate === 'forgotpassword') {
      return `Dear {user},

Somebody (hopefully you) requested a new password for the account for {email}.
Your new password is {password}.
Kindly update your password after login. We'll be here to help you with any step along the way.

Note: Do not reply to this notification message, this message was auto-generated by the sender's security system.

All Rights Reserved.`;
    }
    if (selectedTemplate === 'delete_account') {
      return `Dear {username},

We hope this message finds you well. We regret to inform you that your account has been deleted.`;
    }
    if (selectedTemplate === 'new_order_invoice') {
      return `Dear {customername},

We are pleased to confirm that we have received your order.

Order details:

Order number: #{ordernumber}
Order Date: {orderdate}
Grand Total: {grandtotal}

Click Here: {track_order_url}

Thank you for choosing us.

Sincerely,
{adminname}`;
    }

    return ''; // Default return for empty content
  };

  return (
    <div id="email-templates" className="mb-4">
      <div className="col-12">
        <div className="card border-0 shadow mt-20">
          <form method="POST" action="https://grocerygo.infotechgravity.com/admin/settings/update_email_messages">
            <input type="hidden" name="_token" value="EPWMnGrqmCYxQEUoroZO2GCFEsylUzXarIrDHrb1" autoComplete="off" />
            <div className="card-header p-3 bg-secondary">
              <div className="flex justify-between items-center">
                <h5 className="text-capitalize font-semibold text-lg">Email Templates</h5>
                <select
                  name="template_type"
                  id="template_type"
                  className="form-select"
                  value={selectedTemplate}
                  onChange={handleTemplateChange}
                >
                  <option value="forgotpassword">Forgot password</option>
                  <option value="delete_account">Delete Account</option>
                  <option value="new_order_invoice">New Order Invoice</option>
                  <option value="order_status">Order Status</option>
                  <option value="referral_earning">Referral Earning</option>
                  <option value="user_verification">User Verification</option>
                </select>
              </div>
            </div>

            <div className="card-body">
              <div className="row">
                <div id="templatemenuContent">
                  {selectedTemplate === 'forgotpassword' && (
                    <div id="forgotpassword" className="block">
                      <div className="col-12">
                        <h5 className="text-start mb-2">Forgot password Variable</h5>
                        <p className="mb-1">
                          Username: <span className="text-primary">{templateVariables.user}</span>
                        </p>
                        <p className="mb-1">
                          Useremail: <span className="text-primary">{templateVariables.email}</span>
                        </p>
                        <p className="mb-1">
                          Password: <span className="text-primary">{templateVariables.password}</span>
                        </p>
                      </div>
                      <div className="col-md-12">
                        <div className="form-group">
                          <label className="form-label font-bold">
                            Email Message <span className="text-danger">*</span>
                          </label>
                          <textarea
                            className="form-control"
                            name="forget_password_email_message"
                            cols="50"
                            rows="10"
                            required
                            value={getTemplateContent()} // Set template content here
                          />
                        </div>
                      </div>
                    </div>
                  )}

                  {selectedTemplate === 'delete_account' && (
                    <div id="delete_account" className="block">
                      <div className="col-12">
                        <h5 className="text-start mb-2">Delete Account Variable</h5>
                        <p className="mb-1">
                          Username: <span className="text-primary">{templateVariables.username}</span>
                        </p>
                      </div>
                      <div className="col-md-12">
                        <div className="form-group">
                          <label className="form-label font-bold">
                            Email Message <span className="text-danger">*</span>
                          </label>
                          <textarea
                            className="form-control"
                            name="delete_account_email_message"
                            cols="50"
                            rows="10"
                            required
                            value={getTemplateContent()} // Set template content here
                          />
                        </div>
                      </div>
                    </div>
                  )}

                  {selectedTemplate === 'new_order_invoice' && (
                    <div id="new_order_invoice" className="block">
                      <div className="col-12">
                        <h5 className="text-start mb-2">New Order Invoice Variable</h5>
                        <p className="mb-1">
                          Customer Name: <span className="text-primary">{templateVariables.customername}</span>
                        </p>
                        <p className="mb-1">
                          Order Number: <span className="text-primary">{templateVariables.ordernumber}</span>
                        </p>
                        <p className="mb-1">
                          Order Date: <span className="text-primary">{templateVariables.orderdate}</span>
                        </p>
                        <p className="mb-1">
                          Total Amount: <span className="text-primary">{templateVariables.grandtotal}</span>
                        </p>
                        <p className="mb-1">
                          Track Order URL: <span className="text-primary">{templateVariables.track_order_url}</span>
                        </p>
                        <p className="mb-1">
                          Admin Name: <span className="text-primary">{templateVariables.adminname}</span>
                        </p>
                      </div>
                      <div className="col-md-12">
                        <div className="form-group">
                          <label className="form-label font-bold">
                            Email Message <span className="text-danger">*</span>
                          </label>
                          <textarea
                            className="form-control"
                            name="new_order_invoice_email_message"
                            cols="50"
                            rows="10"
                            required
                            value={getTemplateContent()} // Set template content here
                          />
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Add more template content as needed for order_status, referral_earning, user_verification */}
                </div>
              </div>

              <div className="form-group text-end mt-3">
                <button className="btn btn-primary px-4" type="submit">Save</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default EmailTemplate;
